### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by luckypoem** [FTwOoO/pyShadowsocks#1]
hi.

root@AR:~# ss shadowsocks --cipher_method aes-256-cfb --password my_password remote --listen_port 8099 &
[1] 18713
root@AR:~# Traceback (most recent call last):
  File "/usr/local/bin/ss", line 9, in <module>
    load_entry_point('pyshadowsocks==0.3', 'console_scripts', 'ss')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/root/src/pyshadowsocks/pyshadowsocks/ss.py", line 20, in <module>
    from protocol.socks5ssl.proxy_server import SOCKS5SSLProxyServerProtocol
  File "/root/src/pyshadowsocks/pyshadowsocks/protocol/socks5ssl/proxy_server.py", line 11, in <module>
    from protocol.socks5.socks5_server import SOCKS5ServerStreamProtocol
  File "/root/src/pyshadowsocks/pyshadowsocks/protocol/socks5/socks5_server.py", line 40
    async def connect_to_addr_tcp(self, addr: Socks5AddrHeader):
            ^
SyntaxError: invalid syntax

如何解决？谢谢你

**Comment by FTwO-O** [comment]
需要>=python3.5的版本

**Comment by luckypoem** [comment]
hi.

搞好了。不过在mac上用goagentx做客户端，翻墙速度好慢。你翻墙速度快吗？
我在mac上，编译了pyshadowsocks:

sudo brew install homebrew/dupes/zlib
		export LDFLAGS=-L/usr/local/opt/zlib/lib
		export CPPFLAGS=-I/usr/local/opt/zlib/include
		
		brew install openssl
		brew upgrade openssl
		brew link --force openssl
		pkg-config --modversion openssl
		
		
			wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
			tar Jxvf Python-3.5.2.tar.xz
			cd Python-3.5.2
			./configure 
			make
			make install
			
			cd ~
			pip3 install -U -e git+https://github.com/FTwO-O/pyShadowsocks.git@master#egg=pyshadowsocks
			显示：
			。。。
			Successfully installed pyshadowsocks
			You are using pip version 8.1.1, however version 8.1.2 is available.
			You should consider upgrading via the 'pip install --upgrade pip' command.
			
			然后，
			ss shadowsocks --cipher_method aes-256-cfb --password my-password local
 --remote_host my_vps_ip --remote_port 8099 &

然后设置ff浏览器的socks5代理为127.0.0.1:1080，访问网站时，显示：
unable to connect.

怎么回事？

**Comment by FTwOoO** [comment]
用netstat -a |grep 1080 看看是什么程序在用1080端口？会不会有冲突？
另外你用--socks_port 99999   在本地指定一下socks监听端口看看？
goagentx还好吧，只是个外壳，一直都在用，方便切换Mac的网卡代理设置。
goangenx的AutoProxyConfiguration自带了太多规则，要多删掉自己按需添加，要么反转改成白名单式的，如果你用全局模式都慢的话，那么：

1.  网络连接到你的VPS本来就慢，可以用nping(nmap套件)测试一下TCP端口的PING值和丢包。如果网络环境实在差，可以买个vxTrans服务加速一下端口，对电信尤其有效

2. shadowsocks协议本身被识别了有干扰。这就没办法了，最近也感觉不太好用了，有打算移植Tor的obfs4混淆

**Comment by luckypoem** [comment]
你好。
看了你的文章https://medium.com/@FWTO_O/vpn-ws%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90-7f21809ceaa#.fhs61s67z ，

这个项目:https://github.com/unbit/vpn-ws ,
按它的说明，我安装好了vpn-ws,但是不熟悉如何在mac上添加路由，搜了一下，也是不行。提交的issue的回复，我也是不得要领：
https://github.com/unbit/vpn-ws/issues/6
你可否尝试在你的mac虚拟机上设置路由，看能否顺利翻墙？？
谢谢回复。

**Comment by FTwOoO** [comment]
issus太长没时间看了
其实我表没有安装过这个vpn-ws（因为服务端太麻烦）但最近有在折腾另外一个VPN
其实无非就是这么个思路:
1. 启动客户端之后，ifconfig看看tun起来了没有，ip设置好了没有
2. 用sudo wirehark看一下tun/tap有没有数据包在里面，如果没有。自己ping一下tun的peer ip看能不能抓包得到
3. netstat -rn 看看默认路由改了没有。流量有没有被转发到服务器（看本地的log或者客户端的tun和服务端的tun一起抓包对比看看)

**Comment by luckypoem** [comment]
hi.
root@ar:~# ss shadowsocks --cipher_method aes-256-cfb --password my_password remote --listen_port 8099 &
[1] 29218
root@ar:~# ss: unrecognized option '--cipher_method'

怎么现在没有--cipher_method参数了？

**Comment by FTwOoO** [comment]
不是吧，我一直在用没动过

**Comment by luckypoem** [comment]
root@ar:~# ss -h
Usage: ss [ OPTIONS ]
       ss [ OPTIONS ] [ FILTER ]
   -h, --help		this message
   -V, --version	output version information
   -n, --numeric	don't resolve service names
   -r, --resolve       resolve host names
   -a, --all		display all sockets
   -l, --listening	display listening sockets
   -o, --options       show timer information
   -e, --extended      show detailed socket information
   -m, --memory        show socket memory usage
   -p, --processes	show process using socket
   -i, --info		show internal TCP information
   -s, --summary	show socket usage summary
   -b, --bpf           show bpf filter socket information
   -Z, --context	display process SELinux security contexts
   -z, --contexts	display process and socket SELinux security contexts

   -4, --ipv4          display only IP version 4 sockets
   -6, --ipv6          display only IP version 6 sockets
   -0, --packet	display PACKET sockets
   -t, --tcp		display only TCP sockets
   -u, --udp		display only UDP sockets
   -d, --dccp		display only DCCP sockets
   -w, --raw		display only RAW sockets
   -x, --unix		display only Unix domain sockets
   -f, --family=FAMILY display sockets of type FAMILY

   -A, --query=QUERY, --socket=QUERY
       QUERY := {all|inet|tcp|udp|raw|unix|unix_dgram|unix_stream|unix_seqpacket|packet|netlink}[,QUERY]

   -D, --diag=FILE     Dump raw information about TCP sockets to FILE
   -F, --filter=FILE   read filter information from FILE
       FILTER := [ state TCP-STATE ] [ EXPRESSION ]
root@ar:~#

确实没有--cipher_method参数了。怎么解决？

**Comment by FTwOoO** [comment]
这个ss不是我的那个，引用错了。
which ss看一下在哪，删掉再重装吧

**Comment by luckypoem** [comment]
hi。
我觉得在本地机器上的命令：
ss shadowsocks --cipher_method aes-128-cfb --password 123456 local --remote_host ftwo.me --remote_port 8099 --socks-port 10088
里面的--socks-port写错了，应该是--socks_port
